In [1]:
import pandas as pd
import numpy as np

In [2]:
dcp=pd.read_csv("data/dailyClosingPrices.csv")

In [3]:
dcp

Date        MSFT        AAPL         AMZN         GOOG  \
0     2013-01-02   23.074232   17.010899   257.309998   360.274597   
1     2013-01-03   22.765125   16.796177   258.480011   360.483826   
2     2013-01-04   22.339064   16.328323   259.149994   367.607117   
3     2013-01-07   22.297297   16.232281   268.459991   366.003143   
4     2013-01-08   22.180330   16.275965   266.380005   365.280823   
...          ...         ...         ...          ...          ...   
2132  2021-06-22  265.510010  133.979996  3505.439941  2539.989990   
2133  2021-06-23  265.269989  133.699997  3503.820068  2529.229980   
2134  2021-06-24  266.690002  133.410004  3449.080078  2545.639893   
2135  2021-06-25  265.019989  133.110001  3401.459961  2539.899902   
2136  2021-06-28  268.720001  134.779999  3443.889893  2536.389893   

              FB        TSLA        GOOGL        NVDA      CMCSA  ...  \
0      28.000000    7.072000   361.987000   11.763624  16.523232  ...   
1      27.770000    6.954000   362.197205   11.772869  16.338783  ...   
2      28.760000    6.880000   369.354340   12.161294  16.330206  ...   
3      29.420000    6.868000   367.742737   11.809867  16.257290  ...   
4      29.059999    6.736000   367.017029   11.550920  16.368814  ...   
...          ...         ...          ...         ...        ...  ...   
2132  339.029999  623.710022  2446.610107  755.469971  57.630001  ...   
2133  340.589996  656.570007  2442.540039  762.289978  55.480000  ...   
2134  343.179993  679.820007  2450.000000  768.219971  56.060001  ...   
2135  341.369995  671.869995  2450.169922  761.239990  56.419998  ...   
2136  355.640015  688.719971  2450.719971  799.400024  56.099998  ...   

           GILD        FISV        CSX       ATVI         MELI        ADSK  \
0     30.914343   20.320000  17.286428  10.193955    80.506470   36.939999   
1     30.869030   20.167500  17.449257  10.249812    80.956558   36.369999   
2     31.186171   20.174999  17.946342  10.398766    81.005486   36.360001   
3     31.663931   20.302500  17.534960  10.408074    80.839165   36.090000   
4     31.878086   20.400000  17.577812  10.231194    81.631676   36.299999   
...         ...         ...        ...        ...          ...         ...   
2132  67.050003  108.300003  95.279999  91.879997  1505.000000  286.070007   
2133  66.650002  107.370003  94.660004  90.790001  1532.760010  283.670013   
2134  67.180000  108.500000  95.150002  92.510002  1542.390015  286.959991   
2135  67.879997  108.989998  95.910004  92.260002  1541.719971  288.739990   
2136  67.699997  108.129997  95.320000  95.400002  1570.719971  293.359985   

             ADI        ILMN        NXPI        BIDU  
0      35.887882   55.419998   26.830719  104.120003  
1      35.308777   55.549999   26.695745  104.980003  
2      34.680740   54.759998   26.358315  104.650002  
3      34.786789   50.900002   26.165493  102.290001  
4      34.427891   52.389999   25.596678  101.089996  
...          ...         ...         ...         ...  
2132  163.669998  465.690002  197.399994  187.610001  
2133  163.630005  469.130005  199.149994  189.169998  
2134  167.039993  468.070007  203.830002  194.770004  
2135  167.660004  474.660004  204.169998  202.639999  
2136  170.570007  481.500000  206.179993  205.179993  

[2137 rows x 41 columns]

In [4]:
dcp_msft=dcp['MSFT']
dcp_msft

0        23.074232
1        22.765125
2        22.339064
3        22.297297
4        22.180330
           ...    
2132    265.510010
2133    265.269989
2134    266.690002
2135    265.019989
2136    268.720001
Name: MSFT, Length: 2137, dtype: float64

In [5]:
dcp_msft_open=dcp_msft[:-1].to_numpy()
dcp_msft_close=dcp_msft[1:].to_numpy()

In [6]:
dcp_msft_open

array([ 23.0742321 ,  22.76512527,  22.33906364, ..., 265.26998901,
       266.69000244, 265.01998901])

In [7]:
dcp_msft_close

array([ 22.76512527,  22.33906364,  22.29729652, ..., 266.69000244,
       265.01998901, 268.72000122])

In [21]:
dcp_msft_return=(dcp_msft_close-dcp_msft_open)/(dcp_msft_open)
dcp_msft_return

array([1.79457941e-04, 3.50271466e-04, 3.49574010e-06, ...,
       2.86555444e-05, 3.92126737e-05, 1.94916700e-04])

In [22]:
dcp_msft_return.sum()

0.5882817542140958